<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    public function run()
    {
        // Seed users
        $users = [
            [
                'name' => 'Admin User',
                'email' => 'admin@hospital.com',
                'password' => password_hash('admin123', PASSWORD_DEFAULT),
                'role' => 'admin',
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'John Smith',
                'email' => 'john.smith@hospital.com',
                'password' => password_hash('doctor123', PASSWORD_DEFAULT),
                'role' => 'doctor',
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Mary Johnson',
                'email' => 'mary.johnson@hospital.com',
                'password' => password_hash('nurse123', PASSWORD_DEFAULT),
                'role' => 'nurse',
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Sarah Lee',
                'email' => 'sarah.lee@hospital.com',
                'password' => password_hash('reception123', PASSWORD_DEFAULT),
                'role' => 'receptionist',
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Mike Brown',
                'email' => 'mike.brown@hospital.com',
                'password' => password_hash('pharma123', PASSWORD_DEFAULT),
                'role' => 'pharmacist',
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ];

        $this->db->table('users')->insertBatch($users);

        // Seed doctors
        $doctors = [
            [
                'name' => 'Dr. John Smith',
                'email' => 'john.smith@hospital.com',
                'phone' => '555-0101',
                'specialization' => 'Cardiology',
                'license_number' => 'DOC001',
                'experience_years' => 10,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Dr. Emily Davis',
                'email' => 'emily.davis@hospital.com',
                'phone' => '555-0102',
                'specialization' => 'Pediatrics',
                'license_number' => 'DOC002',
                'experience_years' => 8,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Dr. Michael Wilson',
                'email' => 'michael.wilson@hospital.com',
                'phone' => '555-0103',
                'specialization' => 'Orthopedics',
                'license_number' => 'DOC003',
                'experience_years' => 12,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Dr. Sarah Johnson',
                'email' => 'sarah.johnson@hospital.com',
                'phone' => '555-0104',
                'specialization' => 'Dermatology',
                'license_number' => 'DOC004',
                'experience_years' => 6,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Dr. Robert Brown',
                'email' => 'robert.brown@hospital.com',
                'phone' => '555-0105',
                'specialization' => 'Neurology',
                'license_number' => 'DOC005',
                'experience_years' => 15,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ];

        $this->db->table('doctors')->insertBatch($doctors);

        // Seed patients
        $patients = [
            [
                'name' => 'Alice Johnson',
                'email' => 'alice.johnson@email.com',
                'phone' => '555-1001',
                'address' => '123 Main St, City, State 12345',
                'date_of_birth' => '1985-03-15',
                'gender' => 'female',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Bob Smith',
                'email' => 'bob.smith@email.com',
                'phone' => '555-1002',
                'address' => '456 Oak Ave, City, State 12345',
                'date_of_birth' => '1978-07-22',
                'gender' => 'male',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Carol Williams',
                'email' => 'carol.williams@email.com',
                'phone' => '555-1003',
                'address' => '789 Pine Rd, City, State 12345',
                'date_of_birth' => '1990-11-08',
                'gender' => 'female',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'David Brown',
                'email' => 'david.brown@email.com',
                'phone' => '555-1004',
                'address' => '321 Elm St, City, State 12345',
                'date_of_birth' => '1965-05-30',
                'gender' => 'male',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Eva Davis',
                'email' => 'eva.davis@email.com',
                'phone' => '555-1005',
                'address' => '654 Maple Ln, City, State 12345',
                'date_of_birth' => '1995-01-12',
                'gender' => 'female',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ];

        $this->db->table('patients')->insertBatch($patients);

        // Seed medicines
        $medicines = [
            [
                'name' => 'Aspirin',
                'generic_name' => 'Acetylsalicylic Acid',
                'description' => 'Pain reliever and fever reducer',
                'dosage_form' => 'Tablet',
                'strength' => '325mg',
                'manufacturer' => 'Generic Pharma',
                'batch_number' => 'ASP001',
                'expiry_date' => date('Y-m-d', strtotime('+2 years')),
                'stock_quantity' => 100,
                'unit_price' => 0.10,
                'reorder_level' => 20,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Ibuprofen',
                'generic_name' => 'Ibuprofen',
                'description' => 'Nonsteroidal anti-inflammatory drug',
                'dosage_form' => 'Tablet',
                'strength' => '200mg',
                'manufacturer' => 'Generic Pharma',
                'batch_number' => 'IBU001',
                'expiry_date' => date('Y-m-d', strtotime('+1.5 years')),
                'stock_quantity' => 150,
                'unit_price' => 0.15,
                'reorder_level' => 25,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Amoxicillin',
                'generic_name' => 'Amoxicillin',
                'description' => 'Antibiotic',
                'dosage_form' => 'Capsule',
                'strength' => '500mg',
                'manufacturer' => 'Antibiotic Corp',
                'batch_number' => 'AMX001',
                'expiry_date' => date('Y-m-d', strtotime('+1 year')),
                'stock_quantity' => 80,
                'unit_price' => 0.50,
                'reorder_level' => 15,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Lisinopril',
                'generic_name' => 'Lisinopril',
                'description' => 'ACE inhibitor for hypertension',
                'dosage_form' => 'Tablet',
                'strength' => '10mg',
                'manufacturer' => 'CardioMed',
                'batch_number' => 'LIS001',
                'expiry_date' => date('Y-m-d', strtotime('+2.5 years')),
                'stock_quantity' => 60,
                'unit_price' => 0.30,
                'reorder_level' => 10,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Metformin',
                'generic_name' => 'Metformin Hydrochloride',
                'description' => 'Antidiabetic medication',
                'dosage_form' => 'Tablet',
                'strength' => '500mg',
                'manufacturer' => 'DiabetiCare',
                'batch_number' => 'MET001',
                'expiry_date' => date('Y-m-d', strtotime('+3 years')),
                'stock_quantity' => 90,
                'unit_price' => 0.20,
                'reorder_level' => 18,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Omeprazole',
                'generic_name' => 'Omeprazole',
                'description' => 'Proton pump inhibitor',
                'dosage_form' => 'Capsule',
                'strength' => '20mg',
                'manufacturer' => 'GastroMed',
                'batch_number' => 'OME001',
                'expiry_date' => date('Y-m-d', strtotime('+2 years')),
                'stock_quantity' => 70,
                'unit_price' => 0.40,
                'reorder_level' => 14,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Simvastatin',
                'generic_name' => 'Simvastatin',
                'description' => 'Statin for cholesterol',
                'dosage_form' => 'Tablet',
                'strength' => '20mg',
                'manufacturer' => 'CholestMed',
                'batch_number' => 'SIM001',
                'expiry_date' => date('Y-m-d', strtotime('+2.5 years')),
                'stock_quantity' => 50,
                'unit_price' => 0.35,
                'reorder_level' => 10,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Paracetamol',
                'generic_name' => 'Acetaminophen',
                'description' => 'Pain reliever and fever reducer',
                'dosage_form' => 'Tablet',
                'strength' => '500mg',
                'manufacturer' => 'PainAway',
                'batch_number' => 'PAR001',
                'expiry_date' => date('Y-m-d', strtotime('+1.5 years')),
                'stock_quantity' => 120,
                'unit_price' => 0.08,
                'reorder_level' => 24,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ];

        $this->db->table('medicines')->insertBatch($medicines);

        // Seed wards
        $wards = [
            [
                'name' => 'General Ward',
                'type' => 'general',
                'capacity' => 20,
                'occupied_beds' => 0,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'ICU',
                'type' => 'icu',
                'capacity' => 10,
                'occupied_beds' => 0,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Private Ward',
                'type' => 'private',
                'capacity' => 5,
                'occupied_beds' => 0,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Emergency Ward',
                'type' => 'emergency',
                'capacity' => 15,
                'occupied_beds' => 0,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Pediatric Ward',
                'type' => 'pediatric',
                'capacity' => 12,
                'occupied_beds' => 0,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Maternity Ward',
                'type' => 'maternity',
                'capacity' => 8,
                'occupied_beds' => 0,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ];

        $this->db->table('wards')->insertBatch($wards);
    }
}
